name       = "fortran-shlex"
version    = "1.1.0"
license    = "MIT"
author     = "Federico Perini"
maintainer = "federico.perini@gmail.com"
copyright  = "Copyright 2023-2025, Federico Perini"

[build]
auto-executables = true
auto-tests       = true
auto-examples    = true
module-naming    = "shlex"

[install]
library = true

[fortran]
implicit-typing   = false
implicit-external = false
source-form       = "free"


